library(DBI)
library(RSQLite)
source("R/queries.R")
con <- dbConnect(SQLite(), "C:/Users/Lorenzo/Documents/Desktop project versions/scrapers-uflo/data/prices.db")
cat("Testing get_products...\n")
result <- get_products(con, search = "", category = "", dias = 30, page = 1, page_size = 30)
cat("Rows:", nrow(result), "\n")
if (nrow(result) > 0) print(head(result, 3))
dbDisconnect(con)
